name: vize
description: "Vize is a modern, developer-friendly Flutter package for effortless responsive UIs that match your Figma designs perfectly."
version: 1.0.2
homepage: https://github.com/dilo-studios/vize
repository: https://github.com/dilo-studios/vize

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
